name: coupon-build

on:
  push:
    branches: [ git-action ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
      
    - name: Build with Maven
      run: mvn -f couponservice/pom.xml clean package install -DskipTests
        
    - name: Upload JAR
      uses: actions/upload-artifact@v2.2.4
      with:
        name: couponservice-0.0.1-SNAPSHOT.jar
        path: /home/runner/.m2/repository/com/ideas/springcloud/couponservice/0.0.1-SNAPSHOT/couponservice-0.0.1-SNAPSHOT.jar
        
